### ISSUE TITLE
Broken Link to missing page on Website: List-of-Native-Rule-&-Parameter

### ISSUE THREAD

**Issue by zjhendryx** [Inventory-Profiles-Next/Inventory-Profiles-Next.github.io#1]
List-of-Native-Rule-&-Parameter is linked to from custom-rules/add, however this page is missing from the this repository, and thus the website.

**Comment by blackd** [comment]
https://inventory-profiles-next.github.io/custom-rules/natives/

I'll fix the link

**Comment by blackd** [comment]
fixed in  95ea8fe
